### ISSUE TITLE
Should we change the random happenings on the the dancefloor

### ISSUE THREAD

**Issue by ivanshum2009** [jackbo11/cm1101_team13_game#10]
Should we randomly be buying our friend a drink?

**Comment by ivanshum2009** [comment]
BUG: when you are on the dancefloor, type go (anythings, e.g. abc), happiness will increase.

**Comment by jackbo11** [comment]
This is due to the events. Look out for any messages.

**Comment by jackbo11** [comment]
I have disabled buying a drink for a friend for now because this takes money.
